function out1 = calculate_p0(a,b)
%CALCULATE_P0
%    OUT1 = CALCULATE_P0(A,B)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    23-Apr-2021 19:35:59

out1 = ((a-1.0e2).*(-1.0./2.5e1))./b;
