function out1 = calculate_theta2(kphat,lamda0,theta3)
%CALCULATE_THETA2
%    OUT1 = CALCULATE_THETA2(KPHAT,LAMDA0,THETA3)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    11-Apr-2021 20:59:09

out1 = -lamda0.*theta3-(lamda0.*2.0)./kphat;
