function out1 = calculate_theta1(a1_hat,lamda1)
%CALCULATE_THETA1
%    OUT1 = CALCULATE_THETA1(A1_HAT,LAMDA1)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    22-Apr-2021 18:16:21

out1 = a1_hat.*(3.0./2.0)-lamda1.*(3.0./2.0)+a1_hat.*lamda1-a1_hat.^2-2.0;
