function out1 = calculate_p0(a,b)
%CALCULATE_P0
%    OUT1 = CALCULATE_P0(A,B)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Aug-2021 19:11:30

out1 = ((a-6.4e1).*(-1.0./1.6e1))./b;
