function out1 = calculate_p2(a,b)
%CALCULATE_P2
%    OUT1 = CALCULATE_P2(A,B)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    21-Apr-2021 21:55:27

out1 = -(a-3.0)./b;
