function out1 = calculate_p2(a,b)
%CALCULATE_P2
%    OUT1 = CALCULATE_P2(A,B)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    23-Apr-2021 19:36:00

out1 = -(a-3.0)./b;
