function out1 = calculate_p1(b)
%CALCULATE_P1
%    OUT1 = CALCULATE_P1(B)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    23-Apr-2021 19:35:59

out1 = (4.9e1./2.5e1)./b;
