function out1 = calculate_p0(a,b)
%CALCULATE_P0
%    OUT1 = CALCULATE_P0(A,B)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    21-Apr-2021 21:55:26

out1 = -(a.*9.0-4.0)./b;
