function out1 = calculate_p1(b)
%CALCULATE_P1
%    OUT1 = CALCULATE_P1(B)

%    This function was generated by the Symbolic Math Toolbox version 8.2.
%    03-Aug-2021 19:11:31

out1 = (3.1e1./1.6e1)./b;
